# Generated by Django 5.1.7 on 2026-01-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_errorticket_assigned_to_alter_errorticket_staff_and_more'),
        ('ims', '0003_sale_cancelled'),
    ]

    operations = [
    ]
