# Generated by Django 5.1.7 on 2026-01-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_merge_20260122_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
