# Generated by Django 5.1.7 on 2026-02-05 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_options_alter_activitylog_timestamp_and_more'),
        ('ims', '0005_historicalsale_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Seen', 'Seen')], db_index=True, default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='date_created',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Item is currently available'), ('Restocking', 'Currently out of stock')], db_index=True, default='Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='date_added',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS')], db_index=True, default='Cash', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Item is currently available'), ('Restocking', 'Currently out of stock')], db_index=True, default='Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS')], db_index=True, default='Cash', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', '-date_created'], name='ims_categor_organiz_2f5cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='errorticket',
            index=models.Index(fields=['organization', 'status'], name='ims_errorti_organiz_17a231_idx'),
        ),
        migrations.AddIndex(
            model_name='errorticket',
            index=models.Index(fields=['assigned_to', '-date_added'], name='ims_errorti_assigne_b4c428_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['organization', 'branch'], name='ims_invento_organiz_a597e6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'branch'], name='ims_invento_product_059115_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['status'], name='ims_invento_status_fa2b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='ims_product_organiz_36da09_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='ims_product_product_9c6d20_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', '-date_added'], name='ims_sale_organiz_e8c456_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'completed'], name='ims_sale_branch__e08956_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['staff', '-date_added'], name='ims_sale_staff_i_f0bc55_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['method', '-date_added'], name='ims_sale_method_408ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['sale', '-last_updated'], name='ims_salesit_sale_id_78ec73_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['organization', 'branch'], name='ims_salesit_organiz_b086ef_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', '-created_at'], name='ims_ticketc_ticket__71ca3c_idx'),
        ),
    ]
