# Generated by Django 5.1.7 on 2026-04-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_notification_organization'),
        ('ims', '0007_invoice_invoiceitem_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_org',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'category_name'), name='unique_category_per_org_branch'),
        ),
    ]
