# Generated by Django 5.1.7 on 2026-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_notification_organization'),
        ('ims', '0008_category_unique_per_org_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_per_org',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'product_name'), name='unique_product_per_org_branch'),
        ),
    ]
