# Generated by Django 5.1.7 on 2026-06-18 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_product_unique_per_org_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSaleTemp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('temp_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('date_synced', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.sale')),
            ],
            options={
                'indexes': [models.Index(fields=['temp_id'], name='ims_offline_temp_id_d42c6b_idx')],
            },
        ),
    ]
