# Generated by Django 5.1.7 on 2026-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventory',
            name='count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
