# Generated by Django 5.1.7 on 2026-10-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_alter_historicalinventory_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image for online store display', null=True, upload_to='product_images/'),
        ),
    ]
