# Generated by Django 5.1.7 on 2026-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0013_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_detail',
            field=models.ImageField(blank=True, help_text='Additional detail / angle image for online store display', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary product image for online store display', null=True, upload_to='product_images/'),
        ),
    ]
