# Generated by Django 5.1.7 on 2026-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0014_product_image_detail_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_extra',
            field=models.ImageField(blank=True, help_text='Extra detail / angle image for online store display', null=True, upload_to='product_images/'),
        ),
    ]
