# Generated by Django 5.1.7 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
    ]
