# Generated by Django 5.1.7 on 2026-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_options_alter_activitylog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(db_index=True, default='Main Branch', max_length=200),
        ),
    ]
