# Generated by Django 5.1.7 on 2026-02-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_branch_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_branch_name_per_organization'),
        ),
    ]
