# Generated by Django 5.1.7 on 2026-02-18 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_branch_unique_branch_name_per_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('sales_rep', 'Sales Representative')], db_index=True, default='sales_rep', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this membership active?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='account.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='account.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'organization memberships',
                'indexes': [models.Index(fields=['user', 'is_active'], name='account_org_user_id_59824e_idx'), models.Index(fields=['organization', 'is_active'], name='account_org_organiz_23100c_idx'), models.Index(fields=['branch', 'is_active'], name='account_org_branch__0b3a60_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
