# Generated by Django 5.1.7 on 2026-02-18 21:39

from django.db import migrations


def migrate_users_to_memberships(apps, schema_editor):
    """
    Migrate existing user-organization relationships to the new OrganizationMembership model
    """
    CustomUser = apps.get_model('account', 'CustomUser')
    OrganizationMembership = apps.get_model('account', 'OrganizationMembership')
    
    migrated_count = 0
    skipped_count = 0
    
    for user in CustomUser.objects.all():
        # Skip users without organization (like superusers)
        if not user.organization:
            skipped_count += 1
            continue
        
        # Check if membership already exists (in case migration is run twice)
        if OrganizationMembership.objects.filter(user=user, organization=user.organization).exists():
            skipped_count += 1
            continue
        
        # Create membership
        OrganizationMembership.objects.create(
            user=user,
            organization=user.organization,
            branch=user.branch if user.branch else user.organization.branch_set.first(),
            role=user.role if user.role else 'sales',
            is_active=user.is_active,
        )
        migrated_count += 1
    
    print(f"✅ Migrated {migrated_count} users to OrganizationMembership")
    print(f"⏭️  Skipped {skipped_count} users (no org or already migrated)")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all OrganizationMembership records
    """
    OrganizationMembership = apps.get_model('account', 'OrganizationMembership')
    count = OrganizationMembership.objects.count()
    OrganizationMembership.objects.all().delete()
    print(f"🔄 Deleted {count} OrganizationMembership records")


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_organizationmembership'),
    ]

    operations = [
        migrations.RunPython(migrate_users_to_memberships, reverse_migration),
    ]
