# Generated by Django 5.1.7 on 2026-02-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_migrate_to_multi_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('sales', 'Sales')], db_index=True, default='sales', max_length=100),
        ),
    ]
