# Generated by Django 5.1.7 on 2026-02-18 21:53

from django.db import migrations


def update_sales_rep_to_sales(apps, schema_editor):
    """
    Update any OrganizationMembership records with role='sales_rep' to role='sales'
    """
    OrganizationMembership = apps.get_model('account', 'OrganizationMembership')
    
    updated_count = OrganizationMembership.objects.filter(role='sales_rep').update(role='sales')
    
    if updated_count > 0:
        print(f"✅ Updated {updated_count} membership records from 'sales_rep' to 'sales'")
    else:
        print("⏭️  No membership records to update")


def reverse_update(apps, schema_editor):
    """
    Reverse the migration by changing 'sales' back to 'sales_rep' (for rollback)
    """
    OrganizationMembership = apps.get_model('account', 'OrganizationMembership')
    
    # Note: This only reverts memberships that might have been created as 'sales'
    # after the forward migration ran
    updated_count = OrganizationMembership.objects.filter(role='sales').update(role='sales_rep')
    
    if updated_count > 0:
        print(f"🔄 Reverted {updated_count} membership records from 'sales' to 'sales_rep'")


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_organizationmembership_role'),
    ]

    operations = [
        migrations.RunPython(update_sales_rep_to_sales, reverse_update),
    ]
