# Generated by Django 5.1.7 on 2026-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_notification_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing Store'), ('electronics', 'Electronics Store'), ('grocery', 'Grocery Store'), ('pharmacy', 'Pharmacy'), ('bookstore', 'Bookstore'), ('convenience', 'Convenience Store'), ('accessories', 'Accessories Store'), ('hardware', 'Hardware Store'), ('department', 'Department Store'), ('developer', 'Developer Sandbox'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
