# Generated by Django 5.1.7 on 2026-08-25 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_organization_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('email_body', models.TextField(help_text='HTML or Plain Text content of the newsletter / promotional message')),
                ('target_audience', models.CharField(choices=[('all_owners', 'All Organization Owners'), ('active_subscribers', 'Active Subscribers (Paid)'), ('trial_owners', 'Trial Owners'), ('expired_subscribers', 'Expired Subscribers'), ('selected_owners', 'Selected Owners (Specified Below)')], default='all_owners', help_text='Target segment of organization owners', max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sending', 'Sending...'), ('Sent', 'Sent'), ('Failed', 'Failed')], db_index=True, default='Draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_owners', models.ManyToManyField(blank=True, help_text="Specific owners if 'Selected Owners' target audience is chosen", limit_choices_to={'role': 'owner'}, related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotional Campaign',
                'verbose_name_plural': 'Promotional Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='account.promotionalcampaign')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotional Email Log',
                'verbose_name_plural': 'Promotional Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
