# Generated by Django 5.1.7 on 2026-09-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_promotionalcampaign_promotionalemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customuser',),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_branch',
            field=models.ForeignKey(blank=True, help_text='The branch whose inventory is used for the online store.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_organizations', to='account.branch'),
        ),
    ]
