# Generated by Django 5.1.7 on 2026-09-29 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_systemanalytics_organization_default_branch'),
        ('ims', '0012_alter_historicalinventory_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('shipping_address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=50)),
                ('shipping_address', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Special delivery instructions')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed & Reserved'), ('dispatched', 'Dispatched / In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dispatch_note', models.TextField(blank=True, help_text='Tracking notes, rider info, or courier receipt')),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branch')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.buyer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_orders', to='account.organization')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_order', to='ims.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True, help_text='Display on public store')),
                ('featured', models.BooleanField(default=False, help_text='Show in featured products section')),
                ('custom_title', models.CharField(blank=True, help_text='Optional override for product name', max_length=200)),
                ('custom_description', models.TextField(blank=True, help_text='Product description shown to buyers')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to='ims.inventory')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.onlineorder')),
                ('product_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productlisting')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Coupon code buyers enter at checkout (e.g. SALLAH20)', max_length=50)),
                ('label', models.CharField(blank=True, help_text='Campaign name (e.g. "Black Friday 2026")', max_length=100)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off (%)'), ('fixed', 'Fixed Amount Off')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (e.g. 15 for 15%) or Fixed Amount', max_digits=10)),
                ('scope', models.CharField(choices=[('entire_order', 'Entire Order'), ('product', 'Specific Products Only')], default='entire_order', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('uses', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave empty for no expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_discounts', to='account.organization')),
                ('products', models.ManyToManyField(blank=True, help_text='Selected products if scope is Specific Products', to='ims.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.storediscount'),
        ),
        migrations.CreateModel(
            name='StoreDiscountRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_saved', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.buyer')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='store.storediscount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_redemptions', to='store.onlineorder')),
            ],
        ),
        migrations.CreateModel(
            name='StoreListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable/disable public storefront.')),
                ('tagline', models.CharField(blank=True, help_text='Short slogan or welcome banner', max_length=255)),
                ('announcement', models.TextField(blank=True, help_text='Top announcement banner on the storefront')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('instagram_handle', models.CharField(blank=True, help_text='e.g. yourstore', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp phone with country code', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='The branch whose inventory is used for the online store. Defaults to organization default branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_listings', to='account.branch')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='account.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productlisting',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='store.storelisting'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('store', 'inventory')},
        ),
    ]
