# Generated by Django 5.1.7 on 2026-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='image_detail',
            field=models.ImageField(blank=True, help_text='Override secondary/detail photo', null=True, upload_to='store_products/'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='image',
            field=models.ImageField(blank=True, help_text='Override primary photo', null=True, upload_to='store_products/'),
        ),
    ]
