# Generated by Django 5.1.7 on 2026-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productlisting_image_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelisting',
            name='primary_color',
            field=models.CharField(blank=True, default='#2563eb', help_text='Primary brand/theme color hex (e.g. #2563eb)', max_length=7, null=True),
        ),
    ]
