# Generated by Django 5.1.7 on 2026-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storelisting_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='payment_method',
            field=models.CharField(choices=[('squadco', 'SquadCo (Card / Transfer / USSD)'), ('cod', 'Pay on Delivery / Manual Confirmation')], default='squadco', max_length=50),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
