# Generated by Django 5.1.7 on 2026-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storebankaccount_storepayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='image_extra',
            field=models.ImageField(blank=True, help_text='Override tertiary/extra photo', null=True, upload_to='store_products/'),
        ),
    ]
