# Generated by Django 5.1.7 on 2026-10-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productlisting_image_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelisting',
            name='online_store_email',
            field=models.EmailField(blank=True, help_text="Email to receive order notifications alongside the shop owner's email", max_length=254),
        ),
        migrations.AlterField(
            model_name='storelisting',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Customer support email', max_length=254),
        ),
    ]
