from django.urls import path
from . import views

urlpatterns = [
    path('', views.branchDasboard, name='index'),
    path('branchdash/<str:pk>/', views.dashboard, name='branchdash'),
    path('dashboard/', views.staffDashboard, name='dashboard'),
    path('update_cart/', views.updateCart, name='update_cart'),
    path('update_quantity/', views.updateQuantity, name='update_quantity'),
    path('cart/', views.cart, name='cart'),
    path('completed/<int:pk>/', views.sale_complete, name='completed'),
    path('checkout/', views.checkout, name='checkout'),
    path('category_list/', views.category_list, name='category_list'),
    path('category/<str:pk>/', views.category, name='category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('reciept/<str:pk>/', views.reciept, name='reciept'),
    path('category_delete/', views.delete_category, name='category_delete'),
    path('branchstore/', views.branchStore, name='branchstore'),
    path('store/', views.store, name='store'),
    path('delete_product/', views.delete_product, name='delete_product'),
    path('sales/', views.sales, name='sales'),
    path('sales<int:pk>/', views.sales, name='sales_single'),
    path('sales_delete/', views.sale_delete, name='sales_delete'),
    path('records/', views.record, name='records'),
    path('products/', views.product_category, name='products'),
    path('product/<str:pk>/', views.product, name='product'),
    path('edit_product/', views.edit_product, name='edit_product'),
    path('set_reorder/', views.edit_inventory, name='set_reorder'),
    path('inventorys/', views.inventory_list, name='inventorys'),
    path('branchinv/', views.branchInventory, name='branchinv'),
    path('delete_inventory/', views.delete_inventory, name='delete_inventory'),
    path('staff/', views.staffs, name='staff'),
    path('staff_detail/<str:pk>/', views.staff, name='staff_detail'),
    path('edit_staff/', views.edit_staff, name='edit_staff'),
    path('delete_staff/', views.delete_staff, name='delete_staff'),
    path('restock/', views.restock, name='restock'),
    path('adminrestock/', views.adminRestock, name='adminrestock'),
    path('export_sales', views.export_sales_csv, name= 'export_sales'),
    path('export_profit/<int:pk>/export/', views.export_profit_csv, name= 'export_profit'),
    path('export_audit/<str:pk>/', views.export_audit_csv, name= 'export_audit'),
    path('profitData/<str:pk>/', views.profitData, name='profitData'),
    path('branchaudit/', views.branchAudit, name='branchaudit'),
    path('price_audit/<str:pk>/', views.inventoryAudit, name='price_audit'),
    path('ticket/', views.errorTicket, name='ticket'),
    path('create_ticket/', views.createTicket, name='create_ticket'),
    path('tickets/<str:pk>', views.Ticket, name='tickets'),
    path('branchrep/', views.branchReport, name='branchrep'),
    path('reports/<int:pk>/', views.report, name='reports'),
    path('branchcount/', views.branchCount, name='branchcount'),
    path('count/', views.countView, name='count'),
    path('admincount/<str:pk>/', views.adminCountView, name='admincount'),
    path('addcount/', views.addCount, name='addcount'),
    path('productlist/<str:pk>/', views.inventoryView, name='productlist'),
    path('sale-pdf/', views.sale_pdf, name='sale-pdf'),
]
# watch out if the value of the variance changes or it is stamped to each date
# what happens when users logs in to another POS and makes sale note: should not be possible
