# Generated by Django 5.1.7 on 2026-08-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='model_name',
            field=models.CharField(default='gemini-flash-latest', max_length=150),
        ),
    ]
