# Generated by Django 4.1.1 on 2024-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
