"""
Django settings for ImsV3 project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config


def get_list(value: str):
    return [item.strip() for item in value.split(',') if item.strip()]
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=False)

# Internal IPs for django-debug-toolbar
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

ALLOWED_HOSTS = get_list(config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.lvh.me'))
CSRF_TRUSTED_ORIGINS = get_list(config('CSRF_TRUSTED_ORIGINS', default=''))


# ENV = config('ENV', default='development')  # 'production' or 'development'
ENV = config('ENV', default='development')  # 'production' or 'development'

if ENV == 'production':
    DOMAIN = "marvexqs.com"
else:
    DOMAIN = "lvh.me:8000"

# Admin URL path (customize for security in production)
ADMIN_URL = config('ADMIN_URL', default='myadmin/')

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'cloudinary',
    'cloudinary_storage',
    # "procrastinate.contrib.django",
    'django_celery_beat',
    'django_celery_results',
    'ims.apps.ImsConfig',
    'account.apps.AccountConfig',
    'subscriptions.apps.SubscriptionsConfig',
    'pages.apps.PagesConfig',
    'intelligence.apps.IntelligenceConfig',
    'simple_history',
    'anymail',
]

import sys

# Add django-debug-toolbar in development
if ENV == 'development' and 'test' not in sys.argv:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # subdomain middleware
    'ImsV3.middleware.SubdomainOrganizationMiddleware',
    'ImsV3.middleware.OrganizationContextMiddleware',
    # Force password change middleware (must be after authentication)
    'ImsV3.middleware.ForcePasswordChangeMiddleware',
    # Subscription middleware (must be after authentication and organization)
    'subscriptions.middleware.SubscriptionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# Add debug toolbar middleware in development
if ENV == 'development' and 'test' not in sys.argv:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'ImsV3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'subscriptions.context_processors.squadco_public_key',
                'subscriptions.context_processors.subscription_context',
                'ims.context_processors.ticket_notifications',
                'account.context_processors.organization_role',
                'account.context_processors.active_branch',
                'account.context_processors.notification_count',
                'account.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'ImsV3.wsgi.application'

UNFOLD = {
    "SITE_HEADER": "Marvex Quicksales"
}


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

if config('DB_NAME', default=None):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
            'OPTIONS': {
                'connect_timeout': 10,
                'keepalives': 1,
                'keepalives_idle': 30,
                'keepalives_interval': 10,
                'keepalives_count': 5,
            }
        }
    }
    # Production database SSL configuration (only if enabled)
    db_ssl_mode = config('DB_SSL_MODE', default='disable')
    if ENV == 'production' and db_ssl_mode != 'disable':
        DATABASES['default']['OPTIONS']['sslmode'] = db_ssl_mode
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat Configuration (for scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ============================================================================
# CACHING CONFIGURATION - Redis Cache for Performance
# ============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://redis:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,  # Don't crash if Redis is down
        },
        'KEY_PREFIX': 'quicksales',
        'TIMEOUT': 300,  # Default 5-minute cache timeout
    }
}

# Cache sessions in Redis (reduces database load)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# ============================================================================
# CACHE TIMEOUT SETTINGS (in seconds)
# ============================================================================
CACHE_TIMEOUTS = {
    'organization': 600,  # 10 minutes
    'user_profile': 300,  # 5 minutes
    'subscription': 1800,  # 30 minutes
    'branch': 600,  # 10 minutes
    'product_list': 300,  # 5 minutes
    'inventory': 300,  # 5 minutes
    'sales_summary': 60,  # 1 minute (updates frequently)
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'account.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'  # West Africa Time (UTC+1)

USE_I18N = True

USE_TZ = True


# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')
# EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
# EMAIL_HOST = config('EMAIL_HOST', default=None)
# EMAIL_PORT = config('EMAIL_PORT', cast=int, default=587)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=None)
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=None)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)


EMAIL_BACKEND = config('EMAIL_BACKEND', default='anymail.backends.brevo.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='info@vextechafrica.com')

# Anymail Brevo (Sendinblue) settings
ANYMAIL = {
    "BREVO_API_KEY": config("ANYMAIL_BREVO_API_KEY"),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "ImsV3/static"]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_MANIFEST_STRICT = False



# media files

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

CLOUDINARY_URL = config('CLOUDINARY_URL', default='')
if CLOUDINARY_URL:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = 'login'  # Points to account:login URL

# Subdomain settings
# DOMAIN = "yourdomain.com"



# SUBDOMAIN_URLCONFS = {
#     None: 'ImsV3.urls',  # Main domain
#     'www': 'ImsV3.urls',  # www subdomain
#     'ims': 'ims.urls',  # ims subdomain
# }


SQUAD_PUBLIC_KEY = config('SQUAD_PUBLIC_KEY', default='')
SQUAD_SECRET_KEY = config('SQUAD_SECRET_KEY', default='')
SQUAD_MERCHANT_ID = config('SQUAD_MERCHANT_ID', default='')
SQUAD_API_BASE_URL = config('SQUAD_API_BASE_URL', default='https://sandbox-api-d.squadco.com')


LOGGING_CONFIG = 'logging.config.dictConfig'
# Procrastinate logging settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "procrastinate": {
            "format": "%(asctime)s %(levelname)-7s %(name)s %(message)s"
        },
        "default": {
            "format": "[%(levelname)s] %(name)s: %(message)s"
        },
    },
    "handlers": {
        "procrastinate": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "procrastinate",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "procrastinate": {
            "handlers": ["procrastinate"],
            "level": "DEBUG",
            "propagate": False,
        },
        "ims": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "account": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "ERROR",
    },
}

# Session Configuration - Logout after 30 minutes of inactivity
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Refresh expiry on each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when browser closes

if ENV == 'production':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool, default=True)
    
    # Session Cookie Security
    # SameSite=Lax (not Strict) is required so the session cookie is sent when
    # third-party payment providers (e.g. Squad) redirect back to our domain
    # after completing a transaction. Strict blocks the cookie on cross-site
    # top-level navigations, causing Django to treat the returning user as
    # unauthenticated and redirecting them to the login page.
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    
    # CSRF Cookie Security
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int, default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    SECURE_SSL_REDIRECT = False

# Tauri Desktop Application Settings
TAURI_APP_VERSION = '0.1.0'