# Generated by Django 5.1.7 on 2026-01-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_coupon_payment_coupon_couponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='size',
            field=models.CharField(choices=[('starter', 'Starter'), ('large', 'Large'), ('xl', 'XL')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('growth', 'Growth'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['tier', 'size', 'billing_frequency']},
        ),
    ]
