# Generated by Django 5.1.7 on 2026-01-23 02:22

from django.db import migrations
from decimal import Decimal


def populate_plans(apps, schema_editor):
    """Populate plans with tier/size/frequency structure and delete old ones."""
    Plan = apps.get_model('subscriptions', 'Plan')
    
    # Delete all old plans
    Plan.objects.all().delete()
    
    # Base prices per tier and size
    base_prices = {
        'basic': {
            'starter': Decimal('15000.00'),
            'large': Decimal('25000.00'),
            'xl': Decimal('40000.00'),
        },
        'growth': {
            'starter': Decimal('40000.00'),
            'large': Decimal('75000.00'),
            'xl': Decimal('100000.00'),
        },
        'premium': {
            'starter': Decimal('100000.00'),
            'large': Decimal('150000.00'),
            'xl': Decimal('250000.00'),
        },
    }
    
    # Frequency multipliers and durations
    frequencies = {
        'monthly': {'multiplier': 1.0, 'duration': 30},
        'quarterly': {'multiplier': 0.95, 'duration': 90},
        'annually': {'multiplier': 0.85, 'duration': 365},
    }
    
    # Plan features per tier
    features = {
        'basic': {'max_users': 5, 'max_branches': 1, 'max_products': 100},
        'growth': {'max_users': 20, 'max_branches': 5, 'max_products': 1000},
        'premium': {'max_users': 100, 'max_branches': 50, 'max_products': 10000},
    }
    
    # Create all plan combinations
    for tier in ['basic', 'growth', 'premium']:
        for size in ['starter', 'large', 'xl']:
            for frequency in ['monthly', 'quarterly', 'annually']:
                base_price = base_prices[tier][size]
                multiplier = frequencies[frequency]['multiplier']
                final_price = base_price * Decimal(str(multiplier))
                duration = frequencies[frequency]['duration']
                
                plan_name = f"{tier.capitalize()} {size.capitalize()} {frequency.capitalize()}"
                
                Plan.objects.create(
                    name=plan_name,
                    tier=tier,
                    size=size,
                    billing_frequency=frequency,
                    price=final_price,
                    duration_in_days=duration,
                    max_users=features[tier]['max_users'],
                    max_branches=features[tier]['max_branches'],
                    max_products=features[tier]['max_products'],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_plan_tiers'),
    ]

    operations = [
        migrations.RunPython(populate_plans, migrations.RunPython.noop),
    ]
