# Generated by Django 5.1.7 on 2026-01-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_populate_plan_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('tier', 'size', 'billing_frequency')},
        ),
    ]
