# Generated by Django 5.1.7 on 2026-01-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_plan_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
