# Generated by Django 5.1.7 on 2026-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('growth', 'Growth'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
