# Generated by Django 5.1.7 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='disable_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(
                choices=[
                    ('free', 'Free'),
                    ('basic', 'Basic'),
                    ('growth', 'Growth'),
                    ('premium', 'Premium'),
                    ('invoice', 'Invoice'),
                ],
                default='basic',
                max_length=20,
            ),
        ),
    ]
