# Generated by Django 5.1.7 on 2026-06-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_plan_disable_store_and_invoice_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('squadco', 'SquadCo')], max_length=20, null=True),
        ),
    ]
