# Generated by Django 5.1.7 on 2026-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_payment_currency_plan_price_usd_paymentgatewayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_online_store',
            field=models.BooleanField(default=True, help_text='Enable online storefront, customer catalog link, and web orders for this plan'),
        ),
    ]
